### ISSUE TITLE
壁体内温度を計算するhelmwall関数内の参照間違い？

### ISSUE THREAD

**Issue by udawtr** [satoh-er/open_eeslism#10]
壁体内温度を計算するhelmwall関数内の参照間違いかもしれません。
blhelmlib.c:L154 において、`helmsumpf(1, &Sd->alir, &Tm, &Tie) ;` の呼び出しがあります。この第2引数は、Sd->alir (double型) のポインタです。第3引数はTm (BHELM構造体)のポインタです。
呼び出し先の helmsumpf関数 (L426) では、以下の様に、第2・3引数を配列の様に扱っています。(`a++, u++` の部分)
そのため、`*u` および `a->xxx` の内容は未定義のメモリ領域を参照していると考えられます。

```
void helmsumpf(int N, double *u, BHELM *a, BHELM *b)
{
	int  i ;
	
	for ( i = 0; i < N; i++, a++, u++ )
	{
		b->trs += *u * a->trs ;
		b->so += *u * a->so  ;
		b->sg += *u * a->sg ;
		b->rn += *u * a->rn ;
		b->in += *u * a->in  ;
		b->pnl += *u * a->pnl ;
	}
}
```

該当箇所へのリンク)
https://github.com/satoh-er/open_eeslism/blob/beab312c93c9832712ec4f96a95d713e69b27b47/Source/bl/blhelmlib.c#LL159C9-L159C9

**Comment by satoh-er** [comment]
@udawtr 
helm・・・　というのは、熱負荷や表面温度が何に由来（日射や外気温度、内部発熱など）するのかを要素別に計算し、出力するための関数です。
30年ほど前に宇田川先生がコーディングしたのですが、不具合があり、だれも使用していないコードです。（佐藤も使用したことない）
一式、削除した方がいいのかなぁという感じです。

**Comment by udawtr** [comment]
@satoh-er 
早速ありがとうございます。読み解く際の参考になります。
(ただ、よくよく見ていると、 helmsumpf関数は第一引数が1なので、結果的にメモリ参照はおかしくなかったかもしれませんが。)
